SM/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),

]

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='user_register'),
    path('login/', views.UserLoginView.as_view(), name='user_login'),
    path('logout/', views.UserLogoutView.as_view(), name='user_logout'),
    path('profile/<int:user_id>/', views.UserProfileView.as_view(), name='user_profile'),
    path('reset/', views.UserPasswordResetView.as_view(), name='reset_password'),
    path('reset/done/', views.UserPasswordResetSendView.as_view(), name='password_reset_send'),
    path('confirm/<uidb64>/<token>/', views.UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('confirm/complete/', views.UserPasswordResetCompeleteView.as_view(), name='password_reset_complete'),
    path('follow/<int:user_id>/', views.UserFollowView.as_view(), name='user_follow'),
    path('unfollow/<int:user_id>/', views.UserUnFollowView.as_view(), name='user_unfollow'),
    path('edit_profile/', views.EditUserProfileView.as_view(), name='edit_profile'),

]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('post/<int:post_id>/<slug:post_slug>/', views.PostDetailView.as_view(), name='post_detail'),
    path('post/delete/<int:user_id>/<int:post_id>/', views.PostDeleteView.as_view(), name='post_delete'),
    path('post/update/<int:post_id>/', views.PostUpdateView.as_view(), name='post_update'),
    path('post/create/', views.PostCreateView.as_view(), name='post_create'),
    path('reply/<int:post_id>/<int:comment_id>/', views.PostAddReplyView.as_view(), name='add_reply'),
    path('like/<int:post_id>/', views.PostLikeView.as_view(), name='post_like'),

]

home/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posts')
    body = models.TextField()
    slug = models.SlugField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-created', 'body')

    def __str__(self):
        return f"{self.user} -- {self.slug}"

    def get_absolut_url(self):
        return reverse('home:post_detail', args=(self.id, self.slug))

    def likes_count(self):
        return self.pvotes.count()

    def user_can_like(self, user):
        user_like = user.uvotes.filter(post=self)
        if user_like.exists():
            return True
        return False


class Comments(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='ucomments')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='pcomments')
    reply = models.ForeignKey('self', on_delete=models.CASCADE, related_name='rcomments', blank=True, null=True)
    is_reply = models.BooleanField(default=False)
    body = models.TextField(max_length=400)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user} -- {self.body[:20]}"


class Vote(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='uvotes')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='pvotes')

    def __str__(self):
        return f"{self.user} __LIKED__ {self.post}"

home/forms.py
from django import forms
from .models import Post, Comments


class PostCreateUpdateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('body', )


class CommentCreateForm(forms.ModelForm):
    class Meta:
        model = Comments
        fields = ('body', )
        widgets = {
            'body': forms.Textarea(attrs={'class': 'form-control'})
        }


class CommentReplyForm(forms.ModelForm):
    class Meta:
        model = Comments
        fields = ('body',)


class PostSearchForm(forms.Form):
    search = forms.CharField()

home/views.py
from django.shortcuts import render, redirect
from django.views import View
from .models import Post, Comments, Vote
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from .forms import PostCreateUpdateForm, CommentCreateForm, CommentReplyForm, PostSearchForm
from django.utils.text import slugify
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator


class HomeView(View):
    form_class = PostSearchForm

    def get(self, request):
        posts = Post.objects.all()
        if request.GET.get('search'):
            posts = posts.filter(body__icontains=request.GET['search'])
        return render(request, 'home/index.html', {'posts': posts, 'form': self.form_class})


class PostDetailView(View):
    form_class = CommentCreateForm
    form_class_reply = CommentReplyForm

    def setup(self, request, *args, **kwargs):
        self.post_instance = Post.objects.get(pk=kwargs['post_id'], slug=kwargs['post_slug'])
        return super().setup(request, *args, **kwargs)

    def get(self,request, *args, **kwargs):
        try:
            comments = self.post_instance.pcomments.filter(is_reply=False)
            # can_like = False
            # if request.user.is_authenticated and self.post_instance.user_can_like(request.user):
            #     can_like = True
            return render(request, 'home/detail.html', {'post': self.post_instance,
                                                        'comments': comments,
                                                        'form': self.form_class,
                                                        'reply_form': self.form_class_reply, })
                                                        # 'can_like': can_like
        except ObjectDoesNotExist:
            messages.warning(request, 'Page Not Found', 'warning')
            return redirect('home:home')

    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.user = request.user
            new_comment.post = self.post_instance
            new_comment.save()
            messages.success(request, 'Your Comment Submited Successfully!', 'success')
            return redirect('home:post_detail', self.post_instance.id, self.post_instance.slug)


class PostDeleteView(LoginRequiredMixin, View):
    def get(self, request, post_id, user_id):
        try:
            post = Post.objects.get(pk=post_id)
            if request.user.id == post.user.id:
                post.delete()
                messages.success(request, 'Post Successfully Deleted', 'success')
            else:
                messages.error(request, 'You Can Not Delete This Message', 'danger')
            # user = User.objects.get(pk=user_id)
            # posts = Post.objects.filter(user=user)
            # return render(request, 'accounts/profile.html', {'user': user, 'posts': posts})
            return redirect('accounts:user_profile', post.user.id)
        except ObjectDoesNotExist:
            messages.warning(request, 'Page Not Found', 'warning')
            return redirect('home:home')


class PostUpdateView(LoginRequiredMixin, View):
    form_class = PostCreateUpdateForm

    def setup(self, request, *args, **kwargs):
        try:
            self.post_instance = Post.objects.get(pk=kwargs['post_id'])
        except ObjectDoesNotExist:
            messages.error(request, 'You Can Not Delete This Message', 'danger')
            return redirect('accounts:user_profile', request.user.id)
        return super().setup(request, *args, **kwargs)

    def dispatch(self, request, *args, **kwargs):
        post = self.post_instance
        if post.user.id != request.user.id:
            messages.error(request, 'You Cant Edit This Message', 'danger')
            return redirect('home:home')
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        post = self.post_instance
        form = self.form_class(instance=post)
        return render(request, 'home/update.html', {'form': form})

    def post(self, request, *args, **kwargs):
        post = self.post_instance
        form = self.form_class(request.POST, instance=post)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.slug = slugify(form.cleaned_data['body'][:30])
            new_post.save()
            messages.success(request, 'Your Post Updated', 'success')
            return redirect('home:post_detail', post.id, post.slug)


class PostCreateView(LoginRequiredMixin, View):
    form_class = PostCreateUpdateForm

    def get(self, request, *args, **kwargs):
        form = self.form_class
        return render(request, 'home/create.html', {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.slug = slugify(form.cleaned_data['body'][:30])
            new_post.user = request.user
            new_post.save()
            messages.success(request, 'Your Post Created', 'success')
            return redirect('home:post_detail', new_post.id, new_post.slug)


class PostAddReplyView(LoginRequiredMixin, View):
    form_class = CommentReplyForm

    def post(self, request, post_id, comment_id):
        post = Post.objects.get(id=post_id)
        comment = Comments.objects.get(id=comment_id)
        form = self.form_class(request.POST)
        if form.is_valid():
            reply = form.save(commit=False)
            reply.user = request.user
            reply.post = post
            reply.reply = comment
            reply.is_reply = True
            reply.save()
            messages.success(request, 'Your Comment Submited Successfully!', 'success')
        return redirect('home:post_detail', post.id, post.slug)


class PostLikeView(LoginRequiredMixin, View):
    def get(self, request, post_id):
        post = Post.objects.get(id=post_id)
        like = Vote.objects.filter(post=post, user=request.user)
        if like.exists():
            like.delete()
            messages.warning(request, 'You Unliked This Post!', 'warning')
            # messages.error(request, 'You Have Already Like This Post!', 'danger')
        else:
            Vote.objects.create(post=post, user=request.user)
            messages.success(request, 'You Liked This Post!', 'success')
        return redirect('home:post_detail', post.id, post.slug)

home/templates/home/create.html
{% extends 'base.html' %}


{% block content %}
    <form action="", method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit", value="Create">
    </form>

{% endblock %}

home/templates/home/detail.html
{% extends 'base.html' %}

{% block content %}
        <p><a class="" href="{% url 'accounts:user_profile' post.user.id %}">{{ post.user.username }}</a> -- {{ post.updated|date:"Y-M" }}</p>
        <p>{{ post.body }}</p>
    {% if post.user.id == request.user.id %}
        <a class="btn btn-danger" href="{% url 'home:post_delete' post.user.id post.id %}"> Delete </a>
        <a class="btn btn-info" href="{% url 'home:post_update' post.id %}"> Update </a>
    {% endif %}
    <hr/>
    {% if request.user.is_authenticated %}

<!--        {#}<a href="{% url 'home:post_like' post.id %}" class="{% if can_like %} disable {% endif %}btn btn-info col-md-2"> Like {{ post.likes_count }} </a>{#}-->
        <a href="{% url 'home:post_like' post.id %}" class="btn btn-info col-md-2"> Like {{ post.likes_count }} </a>

        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input class="btn btn-info" type="submit" value="Send Comment">
        </form>
    {% else %}
        <p class="alert alert-warning"> Only Logged in Users Can Comment </p>
    {% endif %}
    <hr/>
    <p>{{ comments.count }} comments</p>
    {% for comment in comments %}
        <div class="card bg-dark text-white">
            <p class="card-header">{{ comment.user }} | {{ comment.created|timesince }}</p>
            <hr/>
            <p class="card-body">{{ comment.body }}</p>

            {% if request.user.is_authenticated %}
                <form class="" action="{% url 'home:add_reply' post.id comment.id %}" method="post">
                    {% csrf_token %}
                    {{ reply_form.as_p }}
                    <input class="btn btn-info" type="submit" value="Send Reply">
                </form>
            {% endif %}

            {% with replies=comment.rcomments.all %}
                {% for reply in replies %}
                <div class="card bg-secondary text-white p-2 m-2">
                    <p class="card-body p-1 m-1"> {{ reply.user }} | {{ comment.created|timesince }}
                    <br/><br/>{{ reply.body }} </p>
                </div>
                {% endfor %}
            {% endwith %}
        </div>
        <br/>
    {% empty %}
        <p> There Is No Reply For This Post.. </p>
    {% endfor %}
{% endblock %}

home/templates/home/index.html
{% extends 'base.html' %}


    {% block content %}
        <form action="" method="get">
            {{ form.as_p }}
            <input class="btn btn-secondary col-md-2" type="submit" value="Search">
        </form>
        <br>
        <br>

        <div class="card">
            {% for post in posts %}
                <a href="{{ post.get_absolut_url }}" class="card-body">{{ post.body|truncatewords:7 }}</a>
            {% endfor %}
        </div>


    {% endblock %}

home/templates/home/update.html
{% extends 'base.html' %}


    {% block content %}
        <form action="", method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit", value="Update">
        </form>

    {% endblock %}