SM/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),

]

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='user_register'),
    path('login/', views.UserLoginView.as_view(), name='user_login'),
    path('logout/', views.UserLogoutView.as_view(), name='user_logout'),
    path('profile/<int:user_id>/', views.UserProfileView.as_view(), name='user_profile'),
    path('reset/', views.UserPasswordResetView.as_view(), name='reset_password'),
    path('reset/done/', views.UserPasswordResetSendView.as_view(), name='password_reset_send'),
    path('confirm/<uidb64>/<token>/', views.UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('confirm/complete/', views.UserPasswordResetCompeleteView.as_view(), name='password_reset_complete'),
    path('follow/<int:user_id>/', views.UserFollowView.as_view(), name='user_follow'),
    path('unfollow/<int:user_id>/', views.UserUnFollowView.as_view(), name='user_unfollow'),
    path('edit_profile/', views.EditUserProfileView.as_view(), name='edit_profile'),

]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('post/<int:post_id>/<slug:post_slug>/', views.PostDetailView.as_view(), name='post_detail'),
    path('post/delete/<int:user_id>/<int:post_id>/', views.PostDeleteView.as_view(), name='post_delete'),
    path('post/update/<int:post_id>/', views.PostUpdateView.as_view(), name='post_update'),
    path('post/create/', views.PostCreateView.as_view(), name='post_create'),
    path('reply/<int:post_id>/<int:comment_id>/', views.PostAddReplyView.as_view(), name='add_reply'),
    path('like/<int:post_id>/', views.PostLikeView.as_view(), name='post_like'),

]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User


class Relation(models.Model):
    from_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='followers')
    to_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='following')
    created =models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.from_user}__FOLLOWING__{self.to_user}'


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    age = models.PositiveSmallIntegerField(default=0)
    bio = models.TextField(null=True, blank=True)

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from .models import Profile


class UserRegisForm(forms.Form):
    username = forms.CharField(max_length=25, widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(label='password', max_length=20,
                                widget=forms.PasswordInput(attrs={'class': 'form-control',
                                                                  'placeholder': 'Max: 20 char'}))
    password2 = forms.CharField(label='Confirm Password', max_length=20,
                                widget=forms.PasswordInput(attrs={'class': 'form-control',
                                                                  'placeholder': 'Max: 20 char'}))

    def clean_email(self):
        email = self.cleaned_data['email']
        user = User.objects.filter(email=email).exists()
        if user:
            raise ValidationError('This Email Already Exist')
        return email

    def clean(self):
        cd = super().clean()
        p1 = cd.get('password1')
        p2 = cd.get('password2')

        if p1 and p2 and p1 != p2:
            raise ValidationError('Passwords Most Match')


class UserLoginForm(forms.Form):
    username = forms.CharField(max_length=25, widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(max_length=20, widget=forms.PasswordInput(attrs={'class': 'form-control',
                                                                                'placeholder': 'Max: 20 char'}))


class EditProfileForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = Profile
        fields = ('age', 'bio')

accounts/views.py
from django.shortcuts import render, redirect
from django.views import View
from .forms import UserRegisForm, UserLoginForm, EditProfileForm
from django.contrib.auth.models import User
from django.contrib import messages
from django.db import IntegrityError
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.contrib.auth import views as auth_view
from .models import Relation


class UserRegisterView(View):
    form_class = UserRegisForm
    temp_name = 'accounts/register.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('home:home')
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        form = UserRegisForm()
        return render(request, self.temp_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data

            try:
                User.objects.create_user(cd['username'], cd['email'], cd['password1'])
                messages.success(request, 'Registered Successfully !', 'success')
                return redirect('accounts:user_login')
            except IntegrityError as e:
                messages.warning(request, 'Username Already Exist !', 'warning')
                return render(request, self.temp_name, {'form': form})

        return render(request, self.temp_name, {'form': form})


class UserLoginView(View):
    form_class = UserLoginForm
    temp_name = 'accounts/login.html'

    def setup(self, request, *args, **kwargs):
        self.next = request.GET.get('next')
        super().setup(self, request, *args, **kwargs)

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('home:home')
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        form = self.form_class()
        return render(request, self.temp_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request, username=cd['username'], password=cd['password'])
            if user:
                login(request, user)
                messages.success(request, 'Logged in Successfully !', 'success')
                if self.next:
                    return redirect(self.next)
                return redirect('home:home')
            messages.warning(request, 'Username OR Password IS Wrong', 'warning')
        return render(request, self.temp_name, {'form': form})


class UserLogoutView(LoginRequiredMixin, View):
    def get(self, request):
        logout(request)
        messages.success(request, 'Logged out Successfully', 'success')
        return redirect('home:home')


class UserProfileView(LoginRequiredMixin, View):
    def get(self, request, user_id):
        is_following = False
        user = User.objects.get(pk=user_id)
        posts = user.posts.all()
        relation = Relation.objects.filter(from_user=request.user, to_user=user)
        if relation.exists():
            is_following = True
        return render(request, 'accounts/profile.html', {'user': user, 'posts': posts, 'is_following': is_following})


class UserPasswordResetView(auth_view.PasswordResetView):
    template_name = 'accounts/email/password_reset_form.html'
    success_url = reverse_lazy('accounts:password_reset_send')
    email_template_name = 'accounts/email/password_reset_email.html'


class UserPasswordResetSendView(auth_view.PasswordResetDoneView):
    template_name = 'accounts/email/password_reset_send.html'


class UserPasswordResetConfirmView(auth_view.PasswordResetConfirmView):
    template_name = 'accounts/email/password_reset_confirm.html'
    success_url = reverse_lazy('accounts:password_reset_complete')


class UserPasswordResetCompeleteView(auth_view.PasswordResetCompleteView):
    template_name = 'accounts/email/password_reset_complete.html'


class UserFollowView(LoginRequiredMixin, View):
    def get(self, request, user_id):
        user = User.objects.get(id=user_id)
        relation = Relation.objects.filter(from_user=request.user, to_user=user)
        if relation.exists():
            messages.warning(request, 'You Already Following This User', 'warning')
        else:
            Relation(from_user=request.user, to_user=user).save()
            messages.success(request, 'You Followed This User', 'success')
        return redirect('accounts:user_profile', user.id)


class UserUnFollowView(LoginRequiredMixin, View):
    def get(self, request, user_id):
        user = User.objects.get(id=user_id)
        relation = Relation.objects.filter(from_user=request.user, to_user=user)
        if relation.exists():
            relation.delete()
            messages.warning(request, 'You UnFollowed This User', 'warning')
        else:
            messages.warning(request, "You are Not Following This User", 'warning')
        return redirect('accounts:user_profile', user.id)


class EditUserProfileView(LoginRequiredMixin, View):
    form_class = EditProfileForm

    def get(self, request):
        form = self.form_class(instance=request.user.profile, initial={'email': request.user.email})
        return render(request, 'accounts/edit_profile.html', {'form': form})

    def post(self, request):
        form = self.form_class(request.POST, instance=request.user.profile)
        if form.is_valid():
            form.save()
            request.user.email = form.cleaned_data['email']
            request.user.save()
            messages.success(request, 'Profile Successfully Edited', 'success')
        return redirect('accounts:user_profile', request.user.id)

accounts/templates/accounts/edit_profile.html
{% extends 'base.html' %}

    {% block content %}

        <form action="" method="post" class="col-md-5 col-lg-5">

            {% csrf_token %}

            {{ form.as_p }}

            <input class="btn btn-success" type="submit" value="Edit">

        </form>

    {% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}


    {% block content %}
        <h1>User Login</h1>

        <form action="" method="post" class="col-md-5 col-lg-5">
            {% csrf_token %}
            {{ form.as_p }}
            <input class="btn btn-success" type="submit" value="Login">
            <br/>
            You Have No Account ?!
            <a class="btn btn-info" href="{% url 'accounts:user_register' %}"> Register </a>
        </form>

    {% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block content %}

    <h1 class="text-center">{{ user.username }}</h1>

    <div class="card">
        {% if request.user.id == user.id %}

        <div class="container text-center">
            <div class="row justify-content-md-center">
                <div class="col col-md-2">
                    <a href="{% url 'home:post_create' %}" class="btn btn-primary "> Create </a>
                </div>
                <div class="col col-md-2">
                    <a href="{% url 'accounts:edit_profile' %}" class="btn btn-primary "> Edit Profile </a>
                </div>
                <div class="col col-md-2">
                    <a href="{% url 'accounts:reset_password' %}" class="btn btn-warning "> Reset Password </a>
                </div>

        {% endif %}

                <div class="col-md-auto">
                    {% if request.user.id != user.id and not is_following %}
                        <a href="{% url 'accounts:user_follow' user.id %}" class="btn btn-success "> Follow </a>
                    {% elif request.user.id != user.id and is_following %}
                        <a href="{% url 'accounts:user_unfollow' user.id %}" class="btn btn-secondary "> UnFollow </a>
                    {% endif %}
                </div>

            </div>
        </div>

        {% for post in posts %}
            <a href="{{ post.get_absolut_url }}" class="card-body">{{ post.body|truncatewords:7 }}</a>
        {% endfor %}
    </div>

{% endblock %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}


    {% block content %}

        <h1>User Register</h1>
        <form action="", method="post", class="col-md-5 col-lg-5">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit", value="Register">
        </form>

    {% endblock %}